config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  match '/register' => "user#register", :as=>"register", via: :post
  match '/club_directory' => "booking#club_directory", :as=>"club_directory", via: :all
  match '/book_time_slot' => "booking#book_time_slot", :as=>"book_time_slot", via: :all
  match '/cancel_time_slot' => "booking#cancel_time_slot", :as=>"cancel_time_slot", via: :all  
  resource :session

  

end

app/models/golf_club.rb
class GolfClub < ActiveRecord::Base
  has_many :tee_time_bookings
end

app/models/tee_time_booking.rb
class TeeTimeBooking < ActiveRecord::Base
  belongs_to :user
  belongs_to  :golf_club
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tee_time_bookings

  validates_uniqueness_of :username
  validates_presence_of :username

  
  def self.authenticate(username)
    user = find_by_username(username)
    return user if user
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController

  def club_directory
    @clubs = GolfClub.all 
  end

  def book_time_slot
    unless current_user.tee_time_bookings.count > 1
      book_time = TeeTimeBooking.new(:timeslot => params[:time_value], :user_id=>current_user.id,:golf_club_id=>params[:golf_club_id])
      book_time.save
      flash[:notice]="You have successfully booked a time slot"

    else
      flash[:notice]="Not allowed to make more than two concurrent bookings"
    end 
    if request.post?       
      respond_to do |format| 
        format.html{redirect_to club_directory_path}
        format.js
       end
    end
  end 

  def cancel_time_slot
    tee_time = TeeTimeBooking.find(params[:time_slot_id])
    tee_time.destroy
    flash[:notice]="Your booking was deleted "
    if request.post?       
      respond_to do |format| 
        format.html{redirect_to club_directory_path}
        format.js
       end
    end
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.authenticate(params[:username])     
      session[:user_id] = user.id
      redirect_to club_directory_path
    else
      flash[:notice] = "Invalid user name"
      redirect_to root_path
    end
  end  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def register
    @user= User.new(user_params)
    if @user.save   
      session[:user_id] = @user.id
      redirect_to club_directory_path
    else
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(:username)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper

  def create_time_slots(time_seperation)
    time = Time.new
    duration_time = []
    start_time = Time.local(time.year,time.month,time.day,9,0,0) 
    end_time =  Time.local(time.year,time.month,time.day,17,0,0) 
    while start_time  <  end_time
      start_time_old = start_time
      start_time += time_seperation.minutes
      duration_time << "#{start_time_old.strftime("%H:%M%p")} - #{start_time.strftime("%H:%M%p")}" 
      start_time += 1.minutes
    end 
    return duration_time
  end 

  def user_booking_restriction(time_slot,user,golf_club)
    time_slot_object = user.tee_time_bookings.where(["timeslot = ? and golf_club_id = ? ",time_slot, golf_club.id])[0]
    booked_status = TeeTimeBooking.where(["timeslot = ? and golf_club_id = ? ", time_slot, golf_club.id])[0]
    return "yes" if time_slot_object.blank? and booked_status.blank?
    return  "booked" if time_slot_object.blank? and !(booked_status.blank?)
    return  time_slot_object if !(time_slot_object.blank?)
  end
    
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/booking/_book_time_slot.html.erb
<%time_slot_id = user_booking_restriction(time_slot,current_user,golf_club)%>
<%if time_slot_id == "yes"%>
  <%=link_to "Book time", book_time_slot_path(:time_value=>time_slot,:golf_club_id=>golf_club.id),:method=>"post"%>
<%else%>
  <%if time_slot_id == "booked"%>
    Booked
  <%else%>
    <%=link_to "Cancel", cancel_time_slot_path(:time_slot_id=>time_slot_id),:method=>"post"%>
  <%end%>
<%end%>

app/views/booking/club_directory.html.erb
<div class="main-container"> 
<% if !flash.empty? %><div class="error_container"><%= flash[:notice] %> </div><% end %> 
  <h1>Golf Club List</h1>
  <%for golf_club in @clubs %>
    <div class="club-entry">
      <h3><%=golf_club.name%><h3>
      <%for time_slot in create_time_slots(20)%>
        <div class="time-slots">
          <%=time_slot%>
          <div class="time-slots__menu">
            <%=render :partial=>"book_time_slot", :locals => {:time_slot => time_slot,:golf_club => golf_club}%>
          </div>
        </div>
      <%end%>
    </div>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Golf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery'%>
  <%= javascript_include_tag 'rails'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="main-container">

  <% if !flash.empty? %><div class="error_container"><%= flash[:notice] %> </div><% end %> 
  <h1>Welcome to the GTA Golf Club management system</h1>
  <div class="main-container__index-menu">

    <div class="main-container__index-menu--signin">
      Already a member?
    </div>

    <div class="main-container__index-menu--register">
      Become a member
    </div>

    <div id="hidden__field--register">
      <%=form_for(:user, :url => register_path) do |f|%>
        Register a unique username
        <p><%=f.text_field(:username,:class=>"index_field")%></p>        
        <%=submit_tag "Register",:class => 'submit_class'%>
      <%end%>
    </div>

    <div id="hidden__field--signin">
      <%=form_tag session_path do %>
        Sign-in with a registered username
        <p><%=text_field_tag(:username,nil,:class=>"index_field")%></p>    
        <%=submit_tag "Sign-in",:class => 'submit_class'%>
      <%end%>
    </div>

  </div>
</div>